version: '3'
services:
  app-teste-fusionist:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: node_app_teste
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      # Anonymous volume:
      - /app/node_modules